apiVersion: v1
kind: Service
metadata:
  name: mail-sender-service
spec:
  selector:
    app: mail-sender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-sender
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 120
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: mail-sender
  template:
    metadata:
      labels:
        app: mail-sender
    spec:
      containers:
        - name: mail-sender
          image: registry.digitalocean.com/hitract/hitract-mail-sender-microservice:#{Build.BuildId}#
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8081
              name: http

          env:
            - name: ENVIRONMENT
              value: "#{ENVIRONMENT}#"
            - name: HITRACT_MYSQL_DB_HOST
              value: "#{HITRACT_MYSQL_DB_HOST}#"
            - name: HITRACT_MYSQL_DB_PORT
              value: "#{HITRACT_MYSQL_DB_PORT}#"
            - name: HITRACT_MYSQL_DB_NAME
              value: "#{HITRACT_MYSQL_DB_NAME}#"
            - name: HITRACT_MYSQL_DB_USERNAME
              value: "#{HITRACT_MYSQL_DB_USERNAME}#"
            - name: HITRACT_MYSQL_DB_PASSWORD
              value: "#{HITRACT_MYSQL_DB_PASSWORD}#"

            - name: HITRACT_REDIS_URL
              value: "#{HITRACT_REDIS_URL}#"
            - name: HITRACT_REDIS_PORT
              value: "#{HITRACT_REDIS_PORT}#"
            - name: HITRACT_REDIS_USERNAME
              value: "#{HITRACT_REDIS_USERNAME}#"
            - name: HITRACT_REDIS_PASSWORD
              value: "#{HITRACT_REDIS_PASSWORD}#"
            - name: HITRACT_REDIS_USE_SSL
              value: "#{HITRACT_REDIS_USE_SSL}#"
            - name: HITRACT_MAILGUN_API_KEY
              value: "#{HITRACT_MAILGUN_API_KEY}#"
            - name: HITRACT_MAILGUN_DOMAIN
              value: "#{HITRACT_MAILGUN_DOMAIN}#"
            - name: HITRACT_MAILGUN_URL
              value: "#{HITRACT_MAILGUN_URL}#"


        - name: wiremock
          image: wiremock/wiremock:latest
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
          - containerPort: 9090
          args: ["--port", "9090"]

