package se.hitract.model.enums;


public enum EntityType {
	
    COMMENT, 
    STUDENT,
    COMPANY_USER,
    COMPANY,
    COURSE,
    COURSE_TOPIC,
    INSTITUTION,
    INSTITUTION_TOPIC,
    INSPIRATION,
    COMPANY_ARTICLE,
    INSTAGRAM_POST,
    GIVEN_CHARACTERISTIC,
    COMPANY_POST,
    STUDENT_REQ_PROFILE,
    TEST, 
    CHAT_MESSAGE, 
    COURSE_TOPIC_POST,
    STUDENT_POST,
    HIT_EVENT,
    HIT_CLUB,
    HIT_CLUB_USER,
    HIT_EVENT_PROMOTER, 
    TICKET, 
    HIT_MEMBER, 
    USER_PRODUCT, 
    PRODUCT_OFFER,
    PRODUCT_BASE,
    ORDER,
    PAYMENT_REPORT,
    HIT_MEMBER_VERSION,
    HIT_PROGRAM,
    MEMBERSHIP_OFFER,
    CHAT_GROUP,
    CHAT_GROUP_PARTICIPANT,
    TRANSACTION,
    SAVED_CARD,
    SUBSCRIPTION,
    INSPIRATION_COLLECTION, HIT_BRAND,

    HIT_DEAL,
    HIT_DEAL_HIT_CLUB,
    PRODUCT

}