package se.hitract.model.enums;

public enum MAIL_TYPE {

    CHAT_NOT_READ,
    COMPANY_SIGNIN,
    COMPANY_SIGNUP,
    STATUS_MAIL,
    HITCLUB_SIGNIN,
    MAIL_SIGNIN,
    HIT_CLUB_INVITE,
    HIT_MEMBER_MANUAL_CREATED,
    PAYMENT_REPORT,
    SPECIAL,
    SPECIAL_M1,
    ORDER_PAYED,
    WEB_ORDER_PAYED,
    USER_PRODUCT_USED,
    USER_PRODUCT_UN_USED,
    CONTACT_INFO,
    WEB_BECOME_MEMBER,
    WEB_MEMBER_STATUS_CHANGED,
    ERROR,
    HIT_CLUB_MEMBER_PAY,
    CONFIRM_EMAIL,
    JONKOPING_PAY_MEMBERSHIP_MAIL,
    RECEIPT,
    PAYPOUT_REPORT_NOT_MATCH

}
